### ISSUE TITLE
ContentViewTwo and ContentViewThree causing issues in test App

### ISSUE THREAD

**Issue by htonkovac** [mazefest/MooCal#2]
Hi, 

I tried to run the Test App but it didn't work at first ... I got a bunch of errors and had to delete ContentViewTwo and ContentViewThree to make it work

Maybe these need to be removed from the project file?

Thanks

**Comment by mazefest** [comment]
Thanks @htonkovac I will take a look at this today, not sure why that is causing issues.

**Comment by mazefest** [comment]
This should be fixed in latest version release.
