### ISSUE TITLE
Add ability to modify MonthView

### ISSUE THREAD

**Issue by htonkovac** [mazefest/MooCal#3]
Hi,

Right now Month titles are static e.g. "November" ... I would like to have more control over the MonthView ... e.g. change it to "November 2024." or even add some contextual data.

Thanks

**Comment by mazefest** [comment]
@htonkovac Agreed, this is on the docket, i might have some time to add that this weekend.

**Comment by mazefest** [comment]
@htonkovac Additional functionality has been added in the latest release `v1.1.0`, for further instructions on how to customize the header view checkout the the wiki [HERE](https://github.com/mazefest/MooCal/wiki/Customization)
